name: Format String
limit: 2000
memory_size: 0x1000
memory_mapped_io:
  0x80: ["Negative %-4d\n-5\n"]
  0x84: []
reports:
  - name: Step-by-step
    slice: all
    view: |
      {pc}:	{instruction}	{pc:label}
  - name: Result
    slice: last
    view: |
      symio[0x80]: {io:0x80:sym}
      symio[0x84]: {io:0x84:sym}
    assert: |
      symio[0x80]: "" >>> ""
      symio[0x84]: "" >>> "Negative -5  "